Repository aragon/aragon.js, pull requests merged in 2018-03, with the labels that each got.

#59 Implement beta templates
  packages/aragon-wrapper/package.json
  packages/aragon-wrapper/src/apm/index.js
  packages/aragon-wrapper/src/ens/index.js
  packages/aragon-wrapper/src/index.js
  packages/aragon-wrapper/src/sandbox.js
  packages/aragon-wrapper/src/templates/index.js
Labels: status: needs review, type: enhancement

#77 Identifiers
  packages/aragon-client/src/index.js
  packages/aragon-wrapper/src/index.js
  packages/aragon-wrapper/src/rpc/handlers/identifier.js
  packages/aragon-wrapper/src/rpc/handlers/index.js
Labels: component: apps, type: enhancement

#79 Add development message provider
  packages/aragon-messenger/src/index.js
  packages/aragon-messenger/src/providers/DevMessage.js
Labels: component: rpc, type: enhancement

#76 External contracts
  packages/aragon-client/src/index.js
  packages/aragon-wrapper/src/index.js
  packages/aragon-wrapper/src/rpc/handlers/external.js
  packages/aragon-wrapper/src/rpc/handlers/index.js
Labels: component: apps, type: enhancement

#80 Use @aragon/apm
  packages/aragon-wrapper/abi/apm/APMRegistry.json
  packages/aragon-wrapper/abi/apm/Repo.json
  packages/aragon-wrapper/package-lock.json
  packages/aragon-wrapper/package.json
  packages/aragon-wrapper/src/apm/index.js
  packages/aragon-wrapper/src/apm/providers/ipfs.js
  packages/aragon-wrapper/src/index.js
Labels: type: enhancement

#72 Make the cache work in not-a-browser
  packages/aragon-wrapper/src/cache/index.js
Labels: component: cache, type: bug

#93 wrapper: Allow wrapper to set accounts manually
  packages/aragon-client/src/index.js
  packages/aragon-wrapper/src/index.js
  packages/aragon-wrapper/src/rpc/handlers/accounts.js
  packages/aragon-wrapper/src/rpc/handlers/index.js
Labels: type: bug
