Repository aragon/aragon.js, pull requests merged in 2018-09, with the labels that each got.

#146 Dedupe request$ across handlers
  packages/aragon-wrapper/src/index.js
Labels: epic: in sprint addition

#131 Support optional transaction parameters in intents
  docs/APP.md
  packages/aragon-wrapper/src/index.js
Labels: epic: dev tooling, epic: in sprint addition

#154 Add Kernel and EVMScriptRegistry artifacts and add old 0.5 Rinkeby DAO app IDs that were generated incorrectly
  packages/aragon-wrapper/abi/aragon/EVMScriptRegistry.json
  packages/aragon-wrapper/artifacts/aragon/EVMScriptRegistry.json
  packages/aragon-wrapper/artifacts/aragon/Kernel.json
  packages/aragon-wrapper/src/core/aragonOS/index.js
  packages/aragon-wrapper/src/interfaces.js
Labels: epic: Permissions
