Repository aragon/aragon.js, pull requests merged in 2019-09, with the labels that each got.

#369 Wrapper: migrate from apm.js and streamline exposed ENS API
  docs/WRAPPER.md
  packages/aragon-wrapper/package.json
  packages/aragon-wrapper/src/core/apm/index.js
  packages/aragon-wrapper/src/core/apm/index.test.js
  packages/aragon-wrapper/src/core/apm/repo.js
  packages/aragon-wrapper/src/ens/index.js
  packages/aragon-wrapper/src/index.js
  packages/aragon-wrapper/src/index.test.js
  packages/aragon-wrapper/src/radspec/index.js
  packages/aragon-wrapper/src/templates/index.js
  packages/aragon-wrapper/src/utils/FileFetcher.js
  packages/aragon-wrapper/src/utils/promise-timeout.js
Labels: breaking-change

#311 messenger: complete multi-emission response streams
  .travis.yml
  package.json
  packages/aragon-rpc-messenger/src/index.js
  packages/aragon-rpc-messenger/src/index.test.js
  packages/aragon-rpc-messenger/src/jsonrpc.js
  packages/aragon-rpc-messenger/src/jsonrpc.test.js
  packages/aragon-rpc-messenger/src/signals.js
  packages/aragon-wrapper/src/index.test.js
  packages/aragon-wrapper/src/rpc/handlers/index.js
  packages/aragon-wrapper/src/rpc/handlers/index.test.js
Labels: enhancement

#384 Wrapper: include hatch.aragonpm.eth's native packages
  packages/aragon-wrapper/src/interfaces.js
Labels: bug
